#include "funciones.h"
void cargarDatosDeEjemplo(tVectorEmpleados empleados, int *maximoLogico)
{
    strcpy(empleados[0].nombres, "LUIS ALBERTO");
    strcpy(empleados[0].apellidos, "SPINETTA");
    empleados[0].fecha.dia = 4;
    empleados[0].fecha.mes = 11;
    empleados[0].fecha.anio = 1978;
    empleados[0].sexo = 'M';
    empleados[0].nacionalidades[0] = 1;
    empleados[0].nacionalidades[1] = 0;
    empleados[0].nacionalidades[2] = 0;
    empleados[0].nacionalidades[3] = 0;
    empleados[0].nacionalidades[4] = 0;
    empleados[0].nacionalidades[5] = 0;
    empleados[0].nacionalidades[6] = 0;
    strcpy(empleados[1].nombres, "CHARLY");
    strcpy(empleados[1].apellidos, "GARCIA");
    empleados[1].fecha.dia = 30;
    empleados[1].fecha.mes = 1;
    empleados[1].fecha.anio = 2010;
    empleados[1].sexo = 'M';
    empleados[1].nacionalidades[0] = 1;
    empleados[1].nacionalidades[1] = 1;
    empleados[1].nacionalidades[2] = 0;
    empleados[1].nacionalidades[3] = 0;
    empleados[1].nacionalidades[4] = 0;
    empleados[1].nacionalidades[5] = 0;
    empleados[1].nacionalidades[6] = 0;
    strcpy(empleados[2].nombres, "MORIA");
    strcpy(empleados[2].apellidos, "CASAN");
    empleados[2].fecha.dia = 2;
    empleados[2].fecha.mes = 2;
    empleados[2].fecha.anio = 1932;
    empleados[2].sexo = 'F';
    empleados[2].nacionalidades[0] = 1;
    empleados[2].nacionalidades[1] = 0;
    empleados[2].nacionalidades[2] = 0;
    empleados[2].nacionalidades[3] = 0;
    empleados[2].nacionalidades[4] = 0;
    empleados[2].nacionalidades[5] = 0;
    empleados[2].nacionalidades[6] = 0;
    strcpy(empleados[3].nombres, "MIRTA");
    strcpy(empleados[3].apellidos, "LEGRAND");
    empleados[3].fecha.dia = 8;
    empleados[3].fecha.mes = 8;
    empleados[3].fecha.anio = 1919;
    empleados[3].sexo = 'F';
    empleados[3].nacionalidades[0] = 0;
    empleados[3].nacionalidades[1] = 0;
    empleados[3].nacionalidades[2] = 0;
    empleados[3].nacionalidades[3] = 0;
    empleados[3].nacionalidades[4] = 0;
    empleados[3].nacionalidades[5] = 0;
    empleados[3].nacionalidades[6] = 1;
    strcpy(empleados[4].nombres, "LALI");
    strcpy(empleados[4].apellidos, "ESPOSITO");
    empleados[4].fecha.dia = 5;
    empleados[4].fecha.mes = 5;
    empleados[4].fecha.anio = 2002;
    empleados[4].sexo = 'F';
    empleados[4].nacionalidades[0] = 1;
    empleados[4].nacionalidades[1] = 1;
    empleados[4].nacionalidades[2] = 1;
    empleados[4].nacionalidades[3] = 0;
    empleados[4].nacionalidades[4] = 1;
    empleados[4].nacionalidades[5] = 1;
    empleados[4].nacionalidades[6] = 1;
    strcpy(empleados[5].nombres, "GRACIELA");
    strcpy(empleados[5].apellidos, "ALFANO");
    empleados[5].fecha.dia = 13;
    empleados[5].fecha.mes = 5;
    empleados[5].fecha.anio = 1940;
    empleados[5].sexo = 'F';
    empleados[5].nacionalidades[0] = 1;
    empleados[5].nacionalidades[1] = 0;
    empleados[5].nacionalidades[2] = 0;
    empleados[5].nacionalidades[3] = 0;
    empleados[5].nacionalidades[4] = 0;
    empleados[5].nacionalidades[5] = 0;
    empleados[5].nacionalidades[6] = 0;
    strcpy(empleados[6].nombres, "GRACIELA");
    strcpy(empleados[6].apellidos, "BORGES");
    empleados[6].fecha.dia = 13;
    empleados[6].fecha.mes = 5;
    empleados[6].fecha.anio = 1940;
    empleados[6].sexo = 'F';
    empleados[6].nacionalidades[0] = 0;
    empleados[6].nacionalidades[1] = 1;
    empleados[6].nacionalidades[2] = 1;
    empleados[6].nacionalidades[3] = 1;
    empleados[6].nacionalidades[4] = 0;
    empleados[6].nacionalidades[5] = 0;
    empleados[6].nacionalidades[6] = 0;
    strcpy(empleados[7].nombres, "FLOR");
    strcpy(empleados[7].apellidos, "DE LA V");
    empleados[7].fecha.dia = 13;
    empleados[7].fecha.mes = 6;
    empleados[7].fecha.anio = 1940;
    empleados[7].sexo = 'F';
    empleados[7].nacionalidades[0] = 0;
    empleados[7].nacionalidades[1] = 0;
    empleados[7].nacionalidades[2] = 1;
    empleados[7].nacionalidades[3] = 0;
    empleados[7].nacionalidades[4] = 0;
    empleados[7].nacionalidades[5] = 0;
    empleados[7].nacionalidades[6] = 0;
    strcpy(empleados[8].nombres, "JORGE LUIS");
    strcpy(empleados[8].apellidos, "BORGES");
    empleados[8].fecha.dia = 12;
    empleados[8].fecha.mes = 12;
    empleados[8].fecha.anio = 1966;
    empleados[8].sexo = 'M';
    empleados[8].nacionalidades[0] = 1;
    empleados[8].nacionalidades[1] = 0;
    empleados[8].nacionalidades[2] = 0;
    empleados[8].nacionalidades[3] = 0;
    empleados[8].nacionalidades[4] = 0;
    empleados[8].nacionalidades[5] = 0;
    empleados[8].nacionalidades[6] = 0;
    strcpy(empleados[9].nombres, "GALA");
    strcpy(empleados[9].apellidos, "CASAN");
    empleados[9].fecha.dia = 21;
    empleados[9].fecha.mes = 3;
    empleados[9].fecha.anio = 2001;
    empleados[9].sexo = 'F';
    empleados[9].nacionalidades[0] = 1;
    empleados[9].nacionalidades[1] = 0;
    empleados[9].nacionalidades[2] = 0;
    empleados[9].nacionalidades[3] = 0;
    empleados[9].nacionalidades[4] = 0;
    empleados[9].nacionalidades[5] = 0;
    empleados[9].nacionalidades[6] = 1;
    *maximoLogico = 10;
}
